language: generic

script:
- npm install -g gitbook-cli
- gitbook build
deploy:
  local_dir: _book
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master